"use strict";
const MANIFEST_URL="./data/manifest.json";
const COLORS=["#02b9a5","#8b5cf6","#ef4444","#0ea5e9","#eab308","#ec4899","#65a30d","#f97316"];
const DAY=86400000;
const state={manifest:null,files:[],cache:new Map(),currentFile:null,currentData:null,periodChart:null,historyChart:null,currentView:"period",historySongKey:""};
const el={};
document.addEventListener("DOMContentLoaded",()=>{cacheElements();bindEvents();loadManifest();});
function cacheElements(){["latestUpdatedAt","refreshButton","loadingPanel","loadingMessage","errorPanel","errorMessage","emptyPanel","appContent","periodPanel","songPanel","periodSelect","periodDescription","periodTopRank","periodTopRankSub","periodBestRank","periodSongCount","periodSnapshotCount","periodSeriesControls","periodChartEmpty","periodChartScroll","periodChartSurface","periodChart","periodTableBody","historySongSelect","historyLoadStatus","historyWeekCount","historyBestRank","historyLatestRank","historyLatestRankSub","historyFirstWeek","historySeriesControls","historyChartEmpty","historyChartScroll","historyChartSurface","historyChart","historyTableBody","historyChartTitle"].forEach(id=>el[id]=document.getElementById(id));}
function bindEvents(){el.refreshButton.addEventListener("click",()=>loadManifest(true));document.querySelectorAll(".view-tab").forEach(btn=>btn.addEventListener("click",()=>switchView(btn.dataset.view)));el.periodSelect.addEventListener("change",()=>{const f=state.files.find(x=>fileKey(x)===el.periodSelect.value);if(f)loadPeriod(f);});el.historySongSelect.addEventListener("change",()=>{state.historySongKey=el.historySongSelect.value;renderHistory();});}
async function loadManifest(preserve=false){showLoading("manifest.jsonを確認しています。");try{const m=await fetchJson(MANIFEST_URL);state.manifest=m;state.files=(Array.isArray(m.files)?m.files:[]).sort((a,b)=>String(b.date).localeCompare(String(a.date)));el.latestUpdatedAt.textContent=formatDateTime(m.updatedAt||m.generatedAt||"");if(!state.files.length){showEmpty();return;}populatePeriods();await preloadAll();const target=preserve&&state.currentFile?state.files.find(f=>fileKey(f)===fileKey(state.currentFile))||state.files[0]:state.files[0];el.periodSelect.value=fileKey(target);await loadPeriod(target);populateSongs();showApp();if(state.currentView==="song")renderHistory();}catch(e){showError(e);}}
async function preloadAll(){for(const f of state.files){if(!state.cache.has(fileKey(f))){try{state.cache.set(fileKey(f),normalize(await fetchJson(resolvePath(f.path))));}catch(e){console.warn(e);}}}}
async function loadPeriod(file){showLoading(`${periodLabel(file.date)}を読み込んでいます。`);let data=state.cache.get(fileKey(file));if(!data){data=normalize(await fetchJson(resolvePath(file.path)));state.cache.set(fileKey(file),data);}state.currentFile=file;state.currentData=data;renderPeriod();showApp();}
function normalize(data){const songs=(Array.isArray(data.songs)?data.songs:[]).map(s=>{const points=(Array.isArray(s.points)?s.points:[]).map(p=>({capturedAt:String(p.capturedAt||""),rank:num(p.rank)})).filter(p=>p.capturedAt&&p.rank!==null).sort((a,b)=>new Date(a.capturedAt)-new Date(b.capturedAt));const ranks=points.map(p=>p.rank);return{...s,songId:String(s.songId||""),songTitle:String(s.songTitle||""),points,currentRank:num(s.currentRank),bestRank:num(s.bestRank)??(ranks.length?Math.min(...ranks):null),worstRank:num(s.worstRank)??(ranks.length?Math.max(...ranks):null)};}).filter(s=>s.songId||s.songTitle);return{...data,period:data.period||{},songs,snapshotCount:Number(data.snapshotCount||0)};}
function populatePeriods(){el.periodSelect.replaceChildren();state.files.forEach(f=>{const o=document.createElement("option");o.value=fileKey(f);o.textContent=periodLabel(f.date);el.periodSelect.append(o);});}
function populateSongs(){const map=new Map();for(const data of state.cache.values())for(const s of data.songs)map.set(songKey(s),s.songTitle||s.songId);el.historySongSelect.replaceChildren();[...map.entries()].sort((a,b)=>a[1].localeCompare(b[1],"ja")).forEach(([k,t])=>{const o=document.createElement("option");o.value=k;o.textContent=t;el.historySongSelect.append(o);});state.historySongKey=state.historySongKey&&map.has(state.historySongKey)?state.historySongKey:(el.historySongSelect.options[0]?.value||"");el.historySongSelect.value=state.historySongKey;}
function renderPeriod(){const d=state.currentData;if(!d)return;el.periodDescription.textContent=`${formatDateTime(d.period.startAt)} 〜 ${formatDateTime(d.period.endAt)} / 最終取得 ${formatDateTime(d.latestCapturedAt)}`;const current=d.songs.map(s=>s.currentRank).filter(v=>v!==null);const best=d.songs.map(s=>s.bestRank).filter(v=>v!==null);el.periodTopRank.textContent=current.length?`${Math.min(...current)}位`:"圏外";el.periodTopRankSub.textContent=`${current.length}/${d.songs.length}曲がランクイン`;el.periodBestRank.textContent=best.length?`${Math.min(...best)}位`:"--";el.periodSongCount.textContent=d.songs.length;el.periodSnapshotCount.textContent=d.snapshotCount||0;renderSeriesControls(el.periodSeriesControls,d.songs.map((s,i)=>({id:songKey(s),label:s.songTitle||s.songId,color:COLORS[i%COLORS.length]})),()=>renderPeriodChart());renderPeriodChart();renderPeriodTable();}
function renderPeriodChart(){const d=state.currentData;if(!d)return;destroy("periodChart");const active=activeIds(el.periodSeriesControls);const songs=d.songs.filter(s=>active.has(songKey(s)));if(!songs.length){toggleChart(el.periodChartEmpty,el.periodChartScroll,false);return;}toggleChart(el.periodChartEmpty,el.periodChartScroll,true);const start=Date.parse(d.period.startAt),end=Date.parse(d.period.endAt);el.periodChartSurface.style.width=`${Math.max(760,7*150)}px`;const datasets=songs.map((s,i)=>({label:s.songTitle||s.songId,data:s.points.filter(p=>{const t=Date.parse(p.capturedAt);return t>=start&&t<end;}).map(p=>({x:Date.parse(p.capturedAt),y:p.rank})),borderColor:COLORS[i%COLORS.length],backgroundColor:COLORS[i%COLORS.length],borderWidth:2.5,pointRadius:2.5,spanGaps:false,tension:.15}));state.periodChart=new Chart(el.periodChart,{type:"line",data:{datasets},options:chartOptions(start,end,true)});}
function renderPeriodTable(){el.periodTableBody.replaceChildren();state.currentData.songs.forEach(s=>{const tr=document.createElement("tr");[s.songTitle||s.songId,rankText(s.currentRank),rankText(s.bestRank),rankText(s.worstRank),formatDateTime(s.firstSeenAt),formatDateTime(s.lastSeenAt)].forEach((v,i)=>{const td=document.createElement("td");td.textContent=v;td.className=i===0?"song-name":i>0&&i<4?"rank-value":"";tr.append(td);});el.periodTableBody.append(tr);});}
function renderHistory(){const key=state.historySongKey;if(!key)return;const weeks=[];state.files.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).forEach(f=>{const d=state.cache.get(fileKey(f));if(!d)return;const s=d.songs.find(x=>songKey(x)===key);if(s)weeks.push({file:f,data:d,song:s});});if(!weeks.length){toggleChart(el.historyChartEmpty,el.historyChartScroll,false);return;}const latest=weeks[weeks.length-1],allRanks=weeks.flatMap(w=>w.song.points.map(p=>p.rank));el.historyWeekCount.textContent=weeks.length;el.historyBestRank.textContent=allRanks.length?`${Math.min(...allRanks)}位`:"--";el.historyLatestRank.textContent=rankText(latest.song.currentRank);el.historyLatestRankSub.textContent=periodLabel(latest.file.date);el.historyFirstWeek.textContent=formatDateKey(weeks[0].file.date);el.historyChartTitle.textContent=`${latest.song.songTitle||latest.song.songId} 全期間比較`;el.historyLoadStatus.textContent=`${weeks.length}週分を重ねて表示しています。`;renderSeriesControls(el.historySeriesControls,weeks.map((w,i)=>({id:fileKey(w.file),label:`${formatDateKey(w.file.date)}開始`,color:`rgba(2,185,165,${0.25+0.75*(i/Math.max(1,weeks.length-1))})`})),()=>renderHistoryChart(weeks));renderHistoryChart(weeks);renderHistoryTable(weeks);}
function renderHistoryChart(weeks){destroy("historyChart");const active=activeIds(el.historySeriesControls),selected=weeks.filter(w=>active.has(fileKey(w.file)));if(!selected.length){toggleChart(el.historyChartEmpty,el.historyChartScroll,false);return;}toggleChart(el.historyChartEmpty,el.historyChartScroll,true);el.historyChartSurface.style.width=`${Math.max(760,7*150)}px`;const start=0,end=7*DAY;const datasets=selected.map((w,i)=>{const base=Date.parse(w.data.period.startAt);const opacity=.25+.75*(weeks.indexOf(w)/Math.max(1,weeks.length-1));const color=`rgba(2,185,165,${opacity})`;return{label:`${formatDateKey(w.file.date)}開始`,data:w.song.points.map(p=>({x:Date.parse(p.capturedAt)-base,y:p.rank})).filter(p=>p.x>=0&&p.x<end),borderColor:color,backgroundColor:color,borderWidth:2.5,pointRadius:2.2,spanGaps:false,tension:.15};});state.historyChart=new Chart(el.historyChart,{type:"line",data:{datasets},options:chartOptions(start,end,false)});}
function renderHistoryTable(weeks){el.historyTableBody.replaceChildren();weeks.slice().reverse().forEach(w=>{const tr=document.createElement("tr");[formatDateKey(w.file.date),rankText(w.song.currentRank),rankText(w.song.bestRank),rankText(w.song.worstRank),formatDateTime(w.song.firstSeenAt),formatDateTime(w.song.lastSeenAt)].forEach((v,i)=>{const td=document.createElement("td");td.textContent=v;td.className=i>0&&i<4?"rank-value":"";tr.append(td);});el.historyTableBody.append(tr);});}
function chartOptions(min,max,absolute){return{responsive:true,maintainAspectRatio:false,interaction:{mode:"nearest",intersect:false},plugins:{legend:{display:false},tooltip:{callbacks:{title(items){if(!items.length)return"";return absolute?formatDateTime(items[0].parsed.x):formatRelative(items[0].parsed.x);},label(c){return`${c.dataset.label}: ${c.parsed.y}位`;}}}},scales:{x:{type:"linear",min,max,ticks:{stepSize:DAY,autoSkip:false,callback(v){return absolute?formatAxis18(v):formatRelative(v);}},grid:{color:"rgba(0,0,0,.08)"}},y:{reverse:true,min:1,max:100,ticks:{stepSize:10,callback:v=>`${v}位`},grid:{color:"rgba(0,0,0,.08)"}}}};}
function renderSeriesControls(container,items,onChange){container.replaceChildren();items.forEach(item=>{const label=document.createElement("label");label.className="series-chip";const input=document.createElement("input");input.type="checkbox";input.checked=true;input.value=item.id;input.addEventListener("change",onChange);const dot=document.createElement("span");dot.className="series-dot";dot.style.background=item.color;const text=document.createElement("span");text.textContent=item.label;label.append(input,dot,text);container.append(label);});}
function activeIds(container){return new Set([...container.querySelectorAll('input[type="checkbox"]:checked')].map(x=>x.value));}
function switchView(view){state.currentView=view;document.querySelectorAll(".view-tab").forEach(b=>b.classList.toggle("is-active",b.dataset.view===view));el.periodPanel.classList.toggle("hidden",view!=="period");el.songPanel.classList.toggle("hidden",view!=="song");if(view==="song")renderHistory();}
function toggleChart(empty,scroll,show){empty.classList.toggle("hidden",show);scroll.classList.toggle("hidden",!show);}
function destroy(name){if(state[name]){state[name].destroy();state[name]=null;}}
function showLoading(msg){el.loadingPanel.classList.remove("hidden");el.loadingMessage.textContent=msg;el.errorPanel.classList.add("hidden");el.emptyPanel.classList.add("hidden");el.appContent.classList.add("hidden");}
function showApp(){el.loadingPanel.classList.add("hidden");el.errorPanel.classList.add("hidden");el.emptyPanel.classList.add("hidden");el.appContent.classList.remove("hidden");}
function showEmpty(){el.loadingPanel.classList.add("hidden");el.errorPanel.classList.add("hidden");el.appContent.classList.add("hidden");el.emptyPanel.classList.remove("hidden");}
function showError(e){console.error(e);el.loadingPanel.classList.add("hidden");el.emptyPanel.classList.add("hidden");el.appContent.classList.add("hidden");el.errorPanel.classList.remove("hidden");el.errorMessage.textContent=e instanceof Error?e.message:String(e);}
async function fetchJson(url){const r=await fetch(`${url}${url.includes("?")?"&":"?"}t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`${r.status} ${r.statusText}: ${url}`);return r.json();}
function resolvePath(p){let s=String(p||"").replace(/^\.\//,"").replace(/^\//,"").replace(/^usen_ranking\//,"");return /^https?:\/\//.test(s)?s:s.startsWith("data/")?`./${s}`:`./data/${s}`;}
function fileKey(f){return String(f.date||f.path||"");}function songKey(s){return s.songId?`id:${s.songId}`:`title:${s.songTitle}`;}function num(v){if(v===null||v===undefined||v==="")return null;const n=Number(v);return Number.isFinite(n)?n:null;}function rankText(v){return v===null||v===undefined?"圏外":`${v}位`;}
function periodLabel(v){return`${formatDateKey(v)} 18:00開始`;}function formatDateKey(v){const m=String(v||"").match(/^(\d{4})(\d{2})(\d{2})$/);return m?`${m[1]}/${m[2]}/${m[3]}`:String(v||"--");}
function formatDateTime(v){if(!v)return"--";const d=new Date(v);if(isNaN(d))return String(v);return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(d);}
function formatAxis18(v){const d=new Date(Number(v));return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(d);}function formatRelative(v){const day=Math.round(Number(v)/DAY);return`${day}日目 18:00`;}
